# Generated by Django 3.2.9 on 2021-11-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_shopuser_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar_url',
        ),
    ]
